# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 624)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QWidget{\n"
"    background:#538FCA;\n"
"}")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 351, 481))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    border: 5px solid #8BCABA;\n"
"}\n"
"QListWidget:item{\n"
"    border-bottom: 2px solid #8BCABA;    \n"
"    background-color:rgba(112,59,202,0.3);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.update_button = QtWidgets.QPushButton(Form)
        self.update_button.setGeometry(QtCore.QRect(20, 520, 111, 61))
        self.update_button.setStyleSheet("QPushButton{\n"
"    background: #615BCA;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #9D97CA;\n"
"}")
        self.update_button.setObjectName("update_button")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setGeometry(QtCore.QRect(140, 520, 111, 61))
        self.delete_button.setStyleSheet("QPushButton{\n"
"    background: #615BCA;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #9D97CA;\n"
"}")
        self.delete_button.setObjectName("delete_button")
        self.choice_button = QtWidgets.QPushButton(Form)
        self.choice_button.setGeometry(QtCore.QRect(260, 520, 111, 61))
        self.choice_button.setStyleSheet("QPushButton{\n"
"    background: #615BCA;\n"
"}\n"
"QPushButton:hover{\n"
"    background: #9D97CA;\n"
"}")
        self.choice_button.setObjectName("choice_button")
        self.name_surname = QtWidgets.QLabel(Form)
        self.name_surname.setGeometry(QtCore.QRect(400, 20, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.name_surname.setFont(font)
        self.name_surname.setStyleSheet("")
        self.name_surname.setAlignment(QtCore.Qt.AlignCenter)
        self.name_surname.setObjectName("name_surname")
        self.text_edit = QtWidgets.QTextEdit(Form)
        self.text_edit.setGeometry(QtCore.QRect(410, 80, 441, 451))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_edit.setFont(font)
        self.text_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_edit.setStyleSheet("QTextEdit{\n"
"    background: white;\n"
"}\n"
"QTextEdit:item{\n"
"    align:left;\n"
"}\n"
"")
        self.text_edit.setObjectName("text_edit")
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(410, 580, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.label_username = QtWidgets.QLabel(Form)
        self.label_username.setGeometry(QtCore.QRect(630, 580, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.input_field = QtWidgets.QLineEdit(Form)
        self.input_field.setGeometry(QtCore.QRect(410, 530, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_field.setFont(font)
        self.input_field.setStyleSheet("QLineEdit{\n"
"    border-top: 3px solid #538FCA;    \n"
"    background: white;\n"
"}")
        self.input_field.setText("")
        self.input_field.setObjectName("input_field")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.update_button.setText(_translate("Form", "Обновить"))
        self.delete_button.setText(_translate("Form", "Удалить"))
        self.choice_button.setText(_translate("Form", "Выбрать"))
        self.name_surname.setText(_translate("Form", "Артемьев Святослав"))
        self.text_edit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_id.setText(_translate("Form", "ID:123456789123456789"))
        self.label_username.setText(_translate("Form", "Username:@XXX_YYY_ZZZ"))
