# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notificated.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 205)
        Form.setStyleSheet("QWidget{\n"
"   background:#538FCA;\n"
"}")
        self.msg = QtWidgets.QLabel(Form)
        self.msg.setGeometry(QtCore.QRect(20, 20, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.msg.setFont(font)
        self.msg.setObjectName("msg")
        self.button_open_window = QtWidgets.QPushButton(Form)
        self.button_open_window.setGeometry(QtCore.QRect(40, 90, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_open_window.setFont(font)
        self.button_open_window.setObjectName("button_open_window")
        self.button_close_window = QtWidgets.QPushButton(Form)
        self.button_close_window.setGeometry(QtCore.QRect(240, 90, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_close_window.setFont(font)
        self.button_close_window.setObjectName("button_close_window")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.msg.setText(_translate("Form", "Новое сообщение(+1) от Артемьева Святослава"))
        self.button_open_window.setText(_translate("Form", "Открыть мессенджер"))
        self.button_close_window.setText(_translate("Form", "Понятно"))
